const projects = [
  {
    id: 'gpt-teacher',
    title: 'Generative Pre-Trained Transformer Teacher',
    img: '/projects/gpt-teacher.png',
    link: '/projects/gpt-teacher',
    date: '2024',
    liveLink: 'https://github.com/ArshdeepSinghVirdi/GPT-Teacher',
    company: 'Generative AI Platform',
    primary: '#1F2A38',
    accentColor: '#C365AA',
    secondary: '#F8F9FA',
    fillColor: '#EBEFF5',
    menuColor: '#1F2A38',
    menuFontColor: '#F8F9FA',
    images: [{ src: '/projects/gpt-teacher.png', tag: 'big', isRight: false }],
    desc: [
      'Traditionally, study materials like presentations, PDFs, and textbook chapters are static and require manual synthesis to create study aids.',
      'GPT-Teacher is an interactive AI-based learning platform where users can upload documents and instantly generate dynamic mindmaps and flowcharts.',
      'It integrates a chat-based Q&A system, YouTube educational content mapping, and robust testing APIs for automated, smart exam preparation.',
    ],
  },
  {
    id: 'coursesphere',
    title: 'CourseSphere - AI Course Generator',
    img: '/projects/coursesphere.jpg',
    link: '/projects/coursesphere',
    date: '2024',
    liveLink: 'https://coursesphere.vercel.app/',
    company: 'AI EdTech Platform',
    primary: '#2B1B3C',
    accentColor: '#AB5A93',
    secondary: '#FBF8FE',
    fillColor: '#F3EBF9',
    menuColor: '#2B1B3C',
    menuFontColor: '#FBF8FE',
    images: [{ src: '/projects/coursesphere.jpg', tag: 'big', isRight: false }],
    desc: [
      'Personalized education is difficult to scale when courses must be constructed manually for every individual skill preference.',
      'CourseSphere is an AI-driven course generator that tailors comprehensive study modules based on customizable user preferences.',
      'To manage monetization, it incorporates a secure payment gateway integration that limits free course generation while enabling premium, unlimited subscription plans.',
    ],
  },
  {
    id: 'finedge',
    title: 'FinEdge - Intelligent Wealth Planner',
    img: '/projects/finedge.jpg',
    link: '/projects/finedge',
    date: '2023',
    liveLink: 'https://github.com/ArshdeepSinghVirdi/FinEdge',
    company: 'Financial Analytics',
    primary: '#0B3A27',
    accentColor: '#2F8A6A',
    secondary: '#F4F8F6',
    fillColor: '#E2EFEA',
    menuColor: '#0B3A27',
    menuFontColor: '#F4F8F6',
    images: [{ src: '/projects/finedge.jpg', tag: 'big', isRight: false }],
    desc: [
      'Keeping track of multiple expenses and predicting future spending habits can be challenging without advanced quantitative tools.',
      'FinEdge is a full-stack personal finance platform that provides smart budgeting, real-time expense tracking, and savings optimization.',
      'It leverages machine learning models for predictive analytics, flags anomaly spending patterns, and feeds back personalized financial advice.',
    ],
  },
  {
    id: 'vigilvault',
    title: 'VigilVault - ATM Threat Intelligence',
    img: '/projects/vigilvault.png',
    link: '/projects/vigilvault',
    date: '2023',
    liveLink: 'https://github.com/ArshdeepSinghVirdi/VigilVault',
    company: 'AI Security System',
    primary: '#3F1212',
    accentColor: '#DC143C',
    secondary: '#FAF5F5',
    fillColor: '#FBEBEB',
    menuColor: '#3F1212',
    menuFontColor: '#FAF5F5',
    images: [{ src: '/projects/vigilvault.png', tag: 'big', isRight: false }],
    desc: [
      'ATM security relies heavily on manual CCTV monitoring, leaving systems vulnerable to delayed security responses during active threats.',
      'VigilVault is an automated, smart threat detection system that monitors feeds in real-time to alert banks to potential security breaches.',
      'Using YOLOv8 for visual object recognition and Isolation Forest models for transaction fraud detection, it maps threat alerts and images to the bank ID via automated emails.',
    ],
  },
  {
    id: 'aigalleryapp',
    title: 'AI Gallery App',
    img: '/projects/aigalleryapp.png',
    link: '/projects/aigalleryapp',
    date: '2023',
    liveLink: 'https://github.com/ArshdeepSinghVirdi/AI-Gallery-App',
    company: 'Mobile Flutter App',
    primary: '#1D3B4D',
    accentColor: '#17A2B8',
    secondary: '#F5FAFC',
    fillColor: '#E7F2F7',
    menuColor: '#1D3B4D',
    menuFontColor: '#F5FAFC',
    images: [{ src: '/projects/aigalleryapp.png', tag: 'big', isRight: false }],
    desc: [
      'Standard mobile galleries only categorize photos by date, offering no intelligent metadata search or on-device creative tools.',
      'AI Gallery App is a high-performance cross-platform Flutter application integrated with Firebase for secure, real-time authentication.',
      'It features semantic, AI-powered image search, smooth vector animations via Rive, and integrated photo editing controls for an all-in-one media experience.',
    ],
  },
  {
    id: 'ecommerce',
    title: 'Full-Stack E-Commerce Platform',
    img: '/projects/ecommerce.jpg',
    link: '/projects/ecommerce',
    date: '2023',
    liveLink: 'https://ecommerce-rho-six-68.vercel.app/auth/login',
    company: 'E-commerce Web App',
    primary: '#2B2B2D',
    accentColor: '#AB5A93',
    secondary: '#FAF7FA',
    fillColor: '#F4EEF3',
    menuColor: '#2B2B2D',
    menuFontColor: '#FAF7FA',
    images: [{ src: '/projects/ecommerce.jpg', tag: 'big', isRight: false }],
    desc: [
      'Businesses need a unified, high-performance checkout and inventory management funnel that operates smoothly under traffic spikes.',
      'This platform is a full-stack e-commerce solution offering responsive browsing, secure customer authentication, and advanced order management.',
      'It features a powerful back-office admin dashboard for monitoring real-time user statistics, listing products, and processing shipments.',
    ],
  },
  {
    id: 'docflow',
    title: 'DocFlow',
    tag: 'Document Approval Web App',
    img: '/projects/DocFlow.jpeg',
    link: '/projects/docflow',
    date: '2024',
    liveLink: 'https://github.com/ArshdeepSinghVirdi/DocFlow/tree/main',
    company: 'DocFlow System',
    primary: '#121824',
    accentColor: '#3B82F6',
    secondary: '#F8FAFC',
    fillColor: '#EFF6FF',
    menuColor: '#121824',
    menuFontColor: '#F8FAFC',
    images: [{ src: '/projects/DocFlow.jpeg', tag: 'big', isRight: false }],
    desc: [
      'DocFlow is a full-stack document approval system designed to streamline pipelines across business departments. Users submit files, which route through multi-stage stages (Initial, Compliance, and Final) based on categories like HR, Policy, and Finance.',
      'Built using React, Vite, Node.js, Express, and Azure SQL Server. Secured with JWT role-based access control defining custom dashboards for Submitter, Approver, and Admin permissions.',
      'Includes administrative controls to configure category approval pipelines, reassign user roles, and monitor system-wide document status statistics.',
    ],
  },
];
export default projects;
